---
- name: Setup & Pre-requisites to install kubernetes
  block: 
    - name: Make sure the br_netfilter module is loaded
      community.general.modprobe:
        name: br_netfilter
        state: present

    - name: Node's iptables to see bridged traffic
      sysctl:
        name: "{{ item }}"
        value: "1"
        sysctl_set: yes
        state: present
        reload: yes
      loop: 
        - net.bridge.bridge-nf-call-ip6tables
        - net.bridge.bridge-nf-call-iptables

    - name: Remove swapfile from /etc/fstab
      mount:
        name: "{{ item }}"
        fstype: swap
        state: absent
      with_items:
        - swap
        - none

    - name: Disable swap
      command: swapoff -a
      when: ansible_swaptotal_mb > 0

- name: Install kubeadm to create a kubernetes cluster
  block:
  - name: Add repo kubernetes from gcp for Debian based
    include_tasks: add-repo-debian.yaml
    when: ansible_facts['os_family'] == 'Debian'
  
  - name: Add repo kubernetes from gcp for Redhat based
    include_tasks: add-repo-debian.yaml
    when: ansible_facts['os_family'] == 'RedHat'

  - name: Install Kubernetes binaries
    package: 
      name: "{{ item }}"
      state: present
      update_cache: yes
    loop:
      - kubelet 
      - kubeadm 
      - kubectl

  - name: Start Kubelet service
    service:
      name: kubelet
      daemon_reload: yes
      enabled: yes
      state: started